import dns from "node:dns"
dns.setServers(['8.8.8.8','8.8.4.4'])

import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./Components/Navbar";
import Footer from "./Components/Footer"
import ToastProvider from "./ToastProvider";
import "react-toastify/dist/ReactToastify.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Qurbani-Mart",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
  lang="en"
  data-theme="light"
  className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
>
  <body className="min-h-full flex flex-col">
    
    <Navbar /> 
         
    
    <main className="flex-grow">
      {children}      
    </main>
    <ToastProvider /> 
    <Footer />       

  </body>
</html>
  );
}
